#! /usr/bin/env bash

while getopts "p:o:n:u:i:" flag; do
    case $flag in
        p)
            port=$OPTARG;;
        o)
            origin=$OPTARG;;
        n)
            name=$OPTARG;;
        u)
            username=$OPTARG;;
        i)
            keyfile=$OPTARG;;
        /?)
            echo "Error: Invalid option"
            exit;;
    esac
done

# make executable file for DNS server
echo "Making DNS server executable"
cp ./dnsserver.py ./dnsserver
chmod +x ./dnsserver
# send to DNS server node
echo "Sending DNS executable to DNS node"
rsync -e "ssh -i $keyfile" ./dnsserver $username@p5-dns.5700.network:~/

# make executable file for HTTP server
echo "Making HTTP server executable"
cp ./httpserver.py ./httpserver
chmod +x ./httpserver
# send to replica node along with data for cache
echo "Sending HTTP executable to replica a node"
rsync -e "ssh -i $keyfile" ./httpserver $username@p5-http-a.5700.network:~/
echo "Sending cache lists to replica a node"
rsync -e "ssh -i $keyfile" ./memory_cache.csv $username@p5-http-a.5700.network:~/
rsync -e "ssh -i $keyfile" ./disk_cache.csv $username@p5-http-a.5700.network:~/
echo "Sending disk_cache.zip to replica a node, this will take several seconds"
rsync -e "ssh -i $keyfile" ./disk_cache.zip $username@p5-http-a.5700.network:~/
