#! /usr/bin/env bash

while getopts "p:o:n:u:i:" flag; do
    case $flag in
        p)
            port=$OPTARG;;
        o)
            origin=$OPTARG;;
        n)
            name=$OPTARG;;
        u)
            username=$OPTARG;;
        i)
            keyfile=$OPTARG;;
        /?)
            echo "Error: Invalid option"
            exit;;
    esac
done

echo "Starting DNS server"
ssh -i $keyfile $username@p5-dns.5700.network "nohup ./dnsserver -p $port -n $name > dnsserver_log.out 2>&1 &"
run_web_server () {
    echo "Starting HTTP server replica $1"
    ssh -i $keyfile $username@p5-http-$1.5700.network "nohup ./httpserver -p $port -o $origin > httpserver_log.out 2>&1 &"
}
replicas=("a" "b" "c" "d" "e" "f" "g")
for i in "${replicas[@]}"; do
    run_web_server "$i" &
done
wait
echo 'Done!'