#! /usr/bin/env bash

while getopts "p:o:n:u:i:" flag; do
    case $flag in
        p)
            port=$OPTARG;;
        o)
            origin=$OPTARG;;
        n)
            name=$OPTARG;;
        u)
            username=$OPTARG;;
        i)
            keyfile=$OPTARG;;
        /?)
            echo "Error: Invalid option"
            exit;;
    esac
done

echo "Stopping DNS server"
ssh -i "$keyfile" "$username@p5-dns.5700.network" "pkill -u $username python"
stop_web_server () {
    echo "Stopping HTTP server replica $1"
    ssh -i "$keyfile" "$username@p5-http-$1.5700.network" "pkill -u $username python"
}
replicas=("a" "b" "c" "d" "e" "f" "g")
for i in "${replicas[@]}"; do
    stop_web_server "$i" &
done
wait
echo 'Done!'